version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "StrongPassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app_network

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    ports:
      - "8080:80"
    depends_on:
      - sql_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
